spring.application.name=PdfBackend
server.port=8081

#spring.data.mongodb.uri=mongodb://localhost:27017/StudentPapers
spring.data.mongodb.uri=mongodb+srv://CampusVault:CampusVault123@cluster1.o4oqcot.mongodb.net/StudentPapers?retryWrites=true&w=majority
#spring.data.mongodb.uri=mongodb+srv://vmaruthi2004_db_user:CampusVault123@campusvault.qmjyc1y.mongodb.net/CampusVault?retryWrites=true&w=majority&tls=true
#spring.data.mongodb.database=StudentPapers


#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=20MB
#spring.servlet.multipart.max-request-size=20MB

jwt.secret=your_super_secret_key_must_be_256bits_long_at_minimum
jwt.expiration=86400000
openrouter.api.key=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