spring.application.name=PdfBackend
server.port=8081

#spring.data.mongodb.uri=mongodb://localhost:27017/StudentPapers
spring.data.mongodb.uri=mongodb+srv://CampusVault:CampusVault123@cluster1.o4oqcot.mongodb.net/StudentPapers?retryWrites=true&w=majority
#spring.data.mongodb.uri=mongodb+srv://vmaruthi2004_db_user:CampusVault123@campusvault.qmjyc1y.mongodb.net/CampusVault?retryWrites=true&w=majority&tls=true
#spring.data.mongodb.database=StudentPapers


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

jwt.secret=your_super_secret_key_must_be_256bits_long_at_minimum
jwt.expiration=86400000

# Tomcat Thread Pool
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20
server.tomcat.accept-count=100
server.tomcat.max-connections=10000

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

#  Cache via Redis
spring.cache.type=redis
spring.cache.redis.time-to-live=60000

#  Spring Session via Redis
spring.session.store-type=redis
spring.session.redis.flush-mode=on_save
spring.session.redis.namespace=campusvault:session


#  Actuator Health Check (NEW: required for load balancer probing) 
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true